# Generated by Django 5.1.2 on 2025-03-01 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_Server", "0007_visitor"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customerorderwaitingtime",
            name="end_time",
        ),
        migrations.RemoveField(
            model_name="customerorderwaitingtime",
            name="start_time",
        ),
        migrations.RemoveField(
            model_name="customerorderwaitingtime",
            name="visual_representation",
        ),
        migrations.AddField(
            model_name="customerorderwaitingtime",
            name="time_before_meal",
            field=models.FloatField(default=0.0),
        ),
    ]
