# Generated by Django 5.1.2 on 2025-03-01 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_Server", "0008_remove_customerorderwaitingtime_end_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerorderwaitingtime",
            name="visual_representation",
            field=models.ImageField(blank=True, null=True, upload_to="order_images/"),
        ),
        migrations.AlterField(
            model_name="customerorderwaitingtime",
            name="date",
            field=models.DateField(),
        ),
    ]
