# Generated by Django 5.1.2 on 2025-03-01 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_Server", "0009_customerorderwaitingtime_visual_representation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerorderwaitingtime",
            name="total_time",
            field=models.FloatField(default=0.0),
        ),
    ]
