# Generated by Django 5.1.2 on 2025-03-01 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_Server", "0010_customerorderwaitingtime_total_time"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerOrderSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("table_number", models.IntegerField()),
                ("total_people", models.IntegerField(default=0)),
                ("people_per_hour", models.JSONField(default=dict)),
                ("meal_counts", models.JSONField(default=dict)),
                (
                    "meal_image",
                    models.ImageField(blank=True, null=True, upload_to="meal_images/"),
                ),
                ("date", models.DateField(auto_now_add=True)),
            ],
        ),
    ]
