# Generated by Django 5.1.2 on 2025-03-02 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_Server", "0011_customerordersummary"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerorderwaitingtime",
            name="total_people",
            field=models.FloatField(default=0.0),
        ),
    ]
