# Generated by Django 5.1.2 on 2025-03-02 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_Server", "0012_customerorderwaitingtime_total_people"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customerordersummary",
            old_name="meal_counts",
            new_name="meals",
        ),
        migrations.AlterField(
            model_name="customerordersummary",
            name="date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="customerordersummary",
            name="total_people",
            field=models.IntegerField(),
        ),
    ]
