# Generated by Django 5.1.2 on 2025-04-10 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_Server", "0013_rename_meal_counts_customerordersummary_meals_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DressCodeEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_key", models.CharField(max_length=20, unique=True)),
                ("data", models.JSONField()),
            ],
        ),
    ]
