# Generated by Django 5.1.2 on 2025-04-12 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_Server", "0014_dresscodeentry"),
    ]

    operations = [
        migrations.CreateModel(
            name="TableCleanliness",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("data", models.JSONField(default=dict)),
            ],
        ),
    ]
